parser: babel-eslint
extends:
  - airbnb-base
env:
  node: true
  es6: true
  jest: true
plugins:
  - import
  - node

overrides:
  files:
    - '**/*.spec.js'
    - '**/*.spec.jsx'

  rules:
    import/first: 0
    import/no-extraneous-dependencies: ["error", {"devDependencies": true}]
